runtime: nodejs22

instance_class: F1

env_variables:
  # The API URL must be updated to the FastAPI App Engine URL once deployed
  NEXT_PUBLIC_API_URL: "https://courtot-gsoc2026.nn.r.appspot.com/api/v1"

handlers:
  - url: /.*
    script: auto
